Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_message.py", line 22, in calc_score
    response = openai.ChatCompletion.create(
  File "/Users/jeanpaul/Library/Python/3.9/lib/python/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeanpaul/Library/Python/3.9/lib/python/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/server1.py", line 96, in new_message_handler
    await group_channels.new_message_handler(event, prompt_c, prompt_a, model_c, model_a,temperature, max_tokens, how_many_hours_verification, collection_messages, collection_channels, collection_channels_score, collection_channels_simiarity)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_group.py", line 21, in new_message_handler
    await message.calc_score(prompt_c, model_c, temperature, max_tokens, collection_messages, self)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_message.py", line 38, in calc_score
    except Error as e:
NameError: name 'Error' is not defined
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_message.py", line 22, in calc_score
    response = openai.ChatCompletion.create(
  File "/Users/jeanpaul/Library/Python/3.9/lib/python/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeanpaul/Library/Python/3.9/lib/python/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/server1.py", line 96, in new_message_handler
    await group_channels.new_message_handler(event, prompt_c, prompt_a, model_c, model_a,temperature, max_tokens, how_many_hours_verification, collection_messages, collection_channels, collection_channels_score, collection_channels_simiarity)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_group.py", line 21, in new_message_handler
    await message.calc_score(prompt_c, model_c, temperature, max_tokens, collection_messages, self)
  File "/Users/jeanpaul/Projects/stage_telegram/server1/class_message.py", line 38, in calc_score
    except Error as e:
NameError: name 'Error' is not defined
